CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
SRC = main.cpp replace.cpp
OBJ = $(SRC:.cpp=.o)
HEADER = Replace.hpp
hamza = replace

all: $(hamza)

$(hamza): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(hamza)

%.o: %.cpp $(HEADER)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(hamza)

re: fclean all